# Generated by Django 3.2.8 on 2022-08-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('min', models.CharField(max_length=100)),
                ('max', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('Base Game', 'Base Game'), ('Expansion', 'Expansion')], default='Base Game', max_length=30)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
