# Generated by Django 5.0.1 on 2025-01-30 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(default='None', max_length=100)),
                ('description', models.CharField(default='None', max_length=1000)),
                ('type', models.CharField(choices=[('Government', 'Government'), ('Public', 'Public'), ('Private', 'Private'), ('Death Star', 'Death Star')], default='Government', max_length=30)),
                ('address_street', models.CharField(default='None', max_length=100)),
                ('city', models.CharField(default='None', max_length=100)),
                ('state', models.CharField(default='None', max_length=100)),
                ('zip', models.CharField(default='None', max_length=100)),
                ('contact', models.CharField(default='None', max_length=100)),
                ('phone', models.CharField(default='None', max_length=100)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='None', max_length=100)),
                ('description', models.CharField(default='None', max_length=1000, verbose_name='Description (Link Share) ')),
                ('image', models.CharField(default='/static/07.png', max_length=1000)),
                ('type', models.CharField(choices=[('Inventory', 'Inventory'), ('Link', 'Link'), ('Tracker', 'Personal Equipment Tracker'), ('Wishlist', 'Public Supply Wishlist'), ('Tool', 'Tool')], default='Tool', max_length=30)),
                ('note', models.CharField(default='None', max_length=1000)),
                ('link', models.CharField(default='None', max_length=1000, verbose_name='Link (Link Share)')),
                ('color', models.CharField(choices=[('border-dark', 'White'), ('border-dark bg-warning', 'Yellow'), ('border-dark bg-info', 'Light Blue'), ('text-white bg-dark', 'Black')], default='border-dark', max_length=30)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('favorited', models.BooleanField(default=False, verbose_name='Favorited')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='None', max_length=1000, verbose_name='Description (Link Share) ')),
                ('link', models.CharField(default='None', max_length=1000, verbose_name='Link (Link Share)')),
                ('color', models.CharField(choices=[('border-dark', 'White'), ('border-dark bg-warning', 'Yellow'), ('border-dark bg-info', 'Light Blue'), ('text-white bg-dark', 'Black')], default='border-dark', max_length=30)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='None', max_length=100)),
                ('first_name', models.CharField(default='None', max_length=100)),
                ('address_street', models.CharField(default='None', max_length=1000)),
                ('city', models.CharField(default='None', max_length=1000)),
                ('state', models.CharField(default='None', max_length=1000)),
                ('zip', models.CharField(default='None', max_length=1000)),
                ('country', models.CharField(default='None', max_length=1000)),
                ('country_code', models.CharField(default='USA', max_length=5)),
                ('region', models.CharField(default='None', max_length=1000)),
                ('phone_primary', models.CharField(default='None', max_length=1000)),
                ('phone_mobile', models.CharField(default='None', max_length=1000)),
                ('email', models.CharField(default='None', max_length=100)),
                ('age_18_plus', models.BooleanField(default=False, verbose_name='18 <= Old')),
                ('e_newsletter', models.BooleanField(default=False, verbose_name='E. Newsletter')),
                ('in_house', models.BooleanField(default=False, verbose_name='In-House')),
                ('registration_p', models.BooleanField(default=False, verbose_name='Registration (Prorated)')),
                ('registration_n_y', models.BooleanField(default=False, verbose_name='Registration (Next Year)')),
                ('remove_mailing_list', models.BooleanField(default=False, verbose_name='Remove from Mailing List')),
                ('no_facility_request', models.BooleanField(default=False, verbose_name="Don't Send Facility Requests")),
                ('owner_id', models.CharField(default='None', max_length=1000)),
                ('web_username', models.CharField(default='None', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('member_since', models.DateField(default='2025-01-01')),
                ('member_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Active', 'Active'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Accepted', max_length=30)),
                ('member_expires', models.DateField(default='2025-01-01')),
                ('evaluator_id', models.CharField(default='None', max_length=1000)),
                ('dsrh_id', models.CharField(default='None', max_length=1000)),
                ('test_score', models.FloatField(default='None', max_length=100000)),
                ('wrong_questions', models.IntegerField(default='None')),
                ('new', models.BooleanField(default=False, verbose_name='New Member')),
                ('ren', models.BooleanField(default=False, verbose_name='Renewed Member')),
                ('sent_dvd', models.BooleanField(default=False, verbose_name='TWT DVD Sent?')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicedex_app.facility')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_id', models.CharField(default='None', max_length=100)),
                ('breed', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Pokemon', 'Pokemon'), ('Robot', 'Robot')], default='Dog', max_length=30)),
                ('dog_name', models.CharField(default='None', max_length=100)),
                ('title', models.CharField(default='None', max_length=100)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('last_printed', models.DateTimeField(default='2025-01-01')),
                ('hrf_date', models.DateField(default='2025-01-01')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('d_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='dicedex_app.member')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Dark', 'Dark'), ('Light', 'Light')], default='Light', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
