# Generated by Django 5.0.1 on 2025-01-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='modified_on',
        ),
    ]
