# Generated by Django 3.2.8 on 2022-08-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.CharField(default='IG88', max_length=100),
        ),
    ]
