# Generated by Django 3.2.8 on 2022-08-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0004_alter_game_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='notes',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
