# Generated by Django 3.2.8 on 2022-08-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0005_game_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='notes',
            new_name='note',
        ),
    ]
