# Generated by Django 5.0.1 on 2025-01-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0005_dog_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='modified',
            field=models.DateTimeField(auto_now=True, default='2025-01-01'),
            preserve_default=False,
        ),
    ]
