# Generated by Django 3.2.8 on 2022-08-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0006_rename_notes_game_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='link',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
