# Generated by Django 5.0.1 on 2025-01-30 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0006_alter_dog_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='d_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='dicedex_app.member'),
        ),
    ]
