# Generated by Django 5.0.1 on 2025-01-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0007_alter_dog_d_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='d_member',
        ),
    ]
