# Generated by Django 5.0.1 on 2025-01-30 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0008_remove_dog_d_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='user',
        ),
    ]
