# Generated by Django 3.2.8 on 2022-09-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0009_auto_20220901_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='owner',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
