# Generated by Django 5.0.1 on 2025-01-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0010_dogo_delete_dog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogo',
            name='d_member',
        ),
        migrations.RemoveField(
            model_name='dogo',
            name='dog_name',
        ),
        migrations.RemoveField(
            model_name='dogo',
            name='hrf_date',
        ),
        migrations.RemoveField(
            model_name='dogo',
            name='last_printed',
        ),
        migrations.RemoveField(
            model_name='dogo',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='dogo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='dogo',
            name='user',
        ),
    ]
