# Generated by Django 3.2.8 on 2022-09-01 02:35

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0010_alter_game_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='user',
            field=models.CharField(max_length=1000, verbose_name=django.contrib.auth.models.User),
        ),
    ]
