# Generated by Django 5.0.1 on 2025-01-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0012_dog_delete_dogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='hrf_date',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='last_printed',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='modified',
        ),
    ]
