# Generated by Django 3.2.8 on 2022-09-01 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0012_auto_20220901_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='user',
        ),
    ]
