# Generated by Django 5.0.1 on 2025-01-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0014_dog_modified_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='hrf_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='dog',
            name='last_printed',
            field=models.DateTimeField(default='2025-01-01'),
        ),
    ]
