# Generated by Django 5.0.1 on 2025-01-30 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0015_dog_hrf_date_dog_last_printed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='last_printed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
