# Generated by Django 3.2.8 on 2022-09-01 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0017_game_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='group',
        ),
    ]
