# Generated by Django 3.2.8 on 2022-09-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0020_rename_owner_game_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='coffee_group',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='hoth_group',
            field=models.BooleanField(default=True),
        ),
    ]
