# Generated by Django 3.2.8 on 2022-09-02 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0021_auto_20220902_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='group',
        ),
    ]
