# Generated by Django 3.2.8 on 2022-09-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0022_remove_game_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gundam_group',
            field=models.BooleanField(default=True),
        ),
    ]
