# Generated by Django 3.2.8 on 2022-09-07 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dicedex_app', '0028_alter_game_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='group',
        ),
        migrations.CreateModel(
            name='G_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
