# Generated by Django 3.2.8 on 2022-09-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0031_game_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Dark', 'Dark'), ('Light', 'Light')], default='Dark', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='group',
        ),
        migrations.DeleteModel(
            name='G_Group',
        ),
    ]
