# Generated by Django 3.2.8 on 2022-09-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0033_auto_20220908_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='wishlist_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='coffee_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='gundam_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='hoth_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='max',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='min',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
