# Generated by Django 3.2.8 on 2022-09-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0034_auto_20220909_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.CharField(default='http://127.0.0.1:8000/static/06.png', max_length=1000),
        ),
    ]
