# Generated by Django 3.2.8 on 2022-09-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0036_alter_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='color',
            field=models.CharField(choices=[('border-dark', 'White'), ('text-white bg-primary', 'Blue'), ('text-white bg-secondary', 'Grey'), ('text-white bg-success', 'Green'), ('text-white bg-danger', 'Red'), ('text-white bg-warning', 'Yellow'), ('text-white bg-info', 'Aqua'), ('text-white bg-dark', 'Dark Grey')], default='border-dark', max_length=30),
        ),
    ]
