# Generated by Django 3.2.8 on 2022-09-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0037_game_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='color',
            field=models.CharField(choices=[('border-dark', 'White'), ('text-white bg-primary', 'Blue'), ('text-white bg-secondary', 'Grey'), ('text-white bg-success', 'Green'), ('text-white bg-danger', 'Red'), ('text-white bg-info', 'Aqua')], default='border-dark', max_length=30),
        ),
    ]
