# Generated by Django 3.2.8 on 2022-09-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0038_alter_game_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.CharField(default='/static/06.png', max_length=1000),
        ),
    ]
