# Generated by Django 5.0.1 on 2024-01-12 20:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0039_alter_game_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Item',
        ),
    ]
