# Generated by Django 5.0.1 on 2024-01-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0040_rename_game_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='genre',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='item',
            name='coffee_group',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='item',
            name='gundam_group',
        ),
        migrations.RemoveField(
            model_name='item',
            name='hoth_group',
        ),
        migrations.RemoveField(
            model_name='item',
            name='length',
        ),
        migrations.RemoveField(
            model_name='item',
            name='max',
        ),
        migrations.RemoveField(
            model_name='item',
            name='min',
        ),
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(default='/static/07.png', max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Link', 'Link'), ('Tool', 'Tool'), ('Inventory', 'Inventory')], default='Link', max_length=30),
        ),
    ]
