# Generated by Django 5.0.1 on 2024-01-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0042_alter_item_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
