# Generated by Django 5.0.1 on 2024-01-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0043_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='wishlist_user',
            field=models.BooleanField(default=False, verbose_name='Spock'),
        ),
    ]
