# Generated by Django 5.0.1 on 2024-01-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0044_alter_item_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='favorited',
            field=models.BooleanField(default=False, verbose_name='Favorited'),
        ),
        migrations.AlterField(
            model_name='item',
            name='event',
            field=models.BooleanField(default=False, verbose_name='Public Suppies Wishlist'),
        ),
        migrations.AlterField(
            model_name='item',
            name='wishlist_user',
            field=models.BooleanField(default=False, verbose_name='Personal Equipment Tracker'),
        ),
    ]
