# Generated by Django 5.0.1 on 2024-01-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0045_item_favorited_alter_item_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='event',
        ),
        migrations.RemoveField(
            model_name='item',
            name='wishlist_user',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(default='None', max_length=1000, verbose_name='Description (Link Share)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.CharField(default='None', max_length=1000, verbose_name='Link (Link Share)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Link', 'Link'), ('Tool', 'Tool'), ('Inventory', 'Inventory'), ('Wishlist', 'Public Supply Wishlist'), ('Tracker', 'Personal Equipment Tracker')], default='Link', max_length=30),
        ),
    ]
