# Generated by Django 5.0.1 on 2024-01-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0047_alter_item_description_alter_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
    ]
