# Generated by Django 5.0.1 on 2024-01-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0048_remove_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
