# Generated by Django 5.0.1 on 2024-02-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0050_alter_item_type_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='user',
        ),
    ]
