# Generated by Django 5.0.1 on 2024-02-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0051_remove_link_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gundam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
