# Generated by Django 5.0.1 on 2024-02-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0052_gundam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='description',
        ),
        migrations.RemoveField(
            model_name='link',
            name='link',
        ),
    ]
