# Generated by Django 5.0.1 on 2024-02-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0053_remove_link_description_remove_link_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gundam',
        ),
        migrations.RemoveField(
            model_name='link',
            name='color',
        ),
        migrations.RemoveField(
            model_name='link',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='link',
            name='label',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
