# Generated by Django 5.0.1 on 2024-02-02 18:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0054_delete_gundam_remove_link_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='label',
        ),
        migrations.AddField(
            model_name='link',
            name='color',
            field=models.CharField(choices=[('border-dark', 'White'), ('border-dark bg-warning', 'Yellow'), ('border-dark bg-info', 'Light Blue'), ('text-white bg-dark', 'Black')], default='border-dark', max_length=30),
        ),
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.CharField(default='None', max_length=1000, verbose_name='Description (Link Share) '),
        ),
        migrations.AddField(
            model_name='link',
            name='link',
            field=models.CharField(default='None', max_length=1000, verbose_name='Link (Link Share)'),
        ),
        migrations.AddField(
            model_name='link',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
