# Generated by Django 5.0.1 on 2025-01-23 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0055_remove_link_label_link_color_link_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='None', max_length=100)),
                ('first_name', models.CharField(default='None', max_length=100)),
                ('address_street', models.CharField(default='None', max_length=1000)),
                ('city', models.CharField(default='None', max_length=1000)),
                ('state', models.CharField(default='None', max_length=1000)),
                ('zip', models.CharField(default='None', max_length=1000)),
                ('country', models.CharField(default='None', max_length=1000)),
                ('region', models.CharField(default='None', max_length=1000)),
                ('phone_primary', models.CharField(default='None', max_length=1000)),
                ('phone_mobile', models.CharField(default='None', max_length=1000)),
                ('email', models.CharField(default='None', max_length=100)),
                ('age_18_plus', models.BooleanField(default=False, verbose_name='Email')),
                ('e_newsletter', models.BooleanField(default=False, verbose_name='E. Newsletter')),
                ('in_house', models.BooleanField(default=False, verbose_name='In-House')),
                ('registration_p', models.BooleanField(default=False, verbose_name='Registration (Prorated)')),
                ('registration_n_y', models.BooleanField(default=False, verbose_name='Registration (Next Year)')),
                ('remove_mailing_list', models.BooleanField(default=False, verbose_name='Remove from Mailing List')),
                ('no_facility_request', models.BooleanField(default=False, verbose_name="Don't Send Facility Requests")),
                ('facility', models.CharField(default='None', max_length=1000)),
                ('owner_id', models.CharField(default='None', max_length=1000)),
                ('web_username', models.CharField(default='None', max_length=100)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('member_since', models.DateField(auto_now_add=True)),
                ('member_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Active', 'Active'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Accepted', max_length=30)),
                ('member_expires', models.DateField(auto_now_add=True)),
                ('evaluator_id', models.CharField(default='None', max_length=1000)),
                ('dsrh_id', models.CharField(default='None', max_length=1000)),
                ('test_score', models.FloatField(default='None', max_length=100000)),
                ('wrong_questions', models.IntegerField(default='None')),
                ('new', models.BooleanField(default=False, verbose_name='New Member')),
                ('ren', models.BooleanField(default=False, verbose_name='Renewed Member')),
                ('sent_dvd', models.BooleanField(default=False, verbose_name='TWT DVD Sent?')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facillity_name', models.CharField(default='None', max_length=100)),
                ('type', models.CharField(choices=[('Government', 'Government'), ('Public', 'Public'), ('Private', 'Private'), ('Death Star', 'Death Star')], default='Government', max_length=30)),
                ('address_street', models.CharField(default='None', max_length=100)),
                ('city', models.CharField(default='None', max_length=100)),
                ('state', models.CharField(default='None', max_length=100)),
                ('zip', models.CharField(default='None', max_length=100)),
                ('contact', models.CharField(default='None', max_length=100)),
                ('phone', models.CharField(default='None', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_id', models.CharField(default='None', max_length=100)),
                ('breed', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Pokemon', 'Pokemon'), ('Robot', 'Robot')], default='Dog', max_length=30)),
                ('dog_name', models.CharField(default='None', max_length=100)),
                ('title', models.CharField(default='None', max_length=100)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('last_printed', models.DateTimeField(auto_now_add=True)),
                ('hrf_date', models.DateField(auto_now_add=True)),
                ('d_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_member', to='dicedex_app.member')),
                ('d_member_expires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_member_expires', to='dicedex_app.member')),
                ('d_member_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_member_status', to='dicedex_app.member')),
            ],
        ),
    ]
