# Generated by Django 5.0.1 on 2025-01-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0058_alter_member_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
