# Generated by Django 5.0.1 on 2025-01-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0059_alter_facility_facility_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
