# Generated by Django 5.0.1 on 2025-01-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0061_member_timestamp_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age_18_plus',
            field=models.BooleanField(default=False, verbose_name='18 <= Old'),
        ),
    ]
