# Generated by Django 5.0.1 on 2025-01-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0062_alter_member_age_18_plus'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='country_code',
            field=models.CharField(default='USA', max_length=3),
        ),
    ]
