# Generated by Django 5.0.1 on 2025-01-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0063_member_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='country_code',
            field=models.CharField(default='USA', max_length=5),
        ),
    ]
