# Generated by Django 5.0.1 on 2025-01-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0064_alter_member_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_expires',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_since',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
