# Generated by Django 5.0.1 on 2025-01-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0065_alter_member_member_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
