# Generated by Django 5.0.1 on 2025-01-29 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0066_member_created_on_alter_member_modified_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='d_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='dicedex_app.member'),
        ),
    ]
