# Generated by Django 5.0.1 on 2025-01-29 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0067_alter_dog_d_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='d_member_expires',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='d_member_status',
        ),
        migrations.AddField(
            model_name='dog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dog',
            name='hrf_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='last_printed',
            field=models.DateTimeField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
