# Generated by Django 5.0.1 on 2025-01-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0068_remove_dog_d_member_expires_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='modified_on',
        ),
    ]
