# Generated by Django 5.0.1 on 2025-01-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0069_remove_dog_modified_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='description',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='facility',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
