# Generated by Django 5.0.1 on 2025-01-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0070_dog_modified_on_facility_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='modified_on',
            field=models.DateTimeField(default='2025-01-01'),
        ),
    ]
