# Generated by Django 5.0.1 on 2025-01-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0076_alter_dog_modified_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
