# Generated by Django 5.0.1 on 2025-01-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0079_alter_dog_modified_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='modified_on',
        ),
    ]
