# Generated by Django 5.0.1 on 2025-01-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0080_remove_dog_modified_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='modified_on',
            field=models.DateTimeField(default='2025-01-01'),
        ),
    ]
