# Generated by Django 5.0.1 on 2025-01-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicedex_app', '0081_dog_modified_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='modified_on',
        ),
        migrations.AddField(
            model_name='dog',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
